module.exports = {
  playerCardsNo: 2,
  communityCardsNo: 5,
  cardValues: {
    two: 0,
    three: 1,
    four: 2,
    five: 3,
    six: 4,
    seven: 5,
    eight: 6,
    nine: 7,
    ten: 8,
    jack: 9,
    queen: 10,
    king: 11,
    ace: 12,
  },
  handRanks: {
    onePair: 100,
    twoPairs: 200,
    threeOfAKind: 300,
    straight: 400,
    flush: 500,
    fullHouse: 600,
    fourOfAKind: 700,
    straightFlush: 800,
    royalFlush: 900,
  },
};
